version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-acs-infra"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yp851rjcxfwr"
s3_prefix = "sam-acs-infra"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["updateACSdbFunction=473090859996.dkr.ecr.eu-west-1.amazonaws.com/samacsinfra12a0f1cc/updateacsdbfunctiona7ae055frepo"]
