AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM ACS Infra
  
Globals:
  Function:
    Timeout: 12
    MemorySize: 256
    Environment:
      Variables:
        STAGE: local
        USERS_CORE_TABLE_NAME: !Ref UserCoreTable

Resources:


#
# cognito
#



#
# dynamoDB
#

  UserCoreTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      UpdateReplacePolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
       

#
#   lambdas functions
#

# add or modify an user of the db
  updateACSdbFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        updateACSbd:
          Type: Api
          Properties:
            Path: /updateACSdb
            Method: any
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserCoreTable

    Metadata:
      DockerTag: python3.8-v1
      DockerContext: ../
      Dockerfile: lambdas/updateACSdb/Dockerfile

# fetch data from user db: it can query by id or fetch all dat
  getACSUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        updateACSbd:
          Type: Api
          Properties:
            Path: /getACSUsers
            Method: any
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserCoreTable

    Metadata:
      DockerTag: python3.8-v1
      DockerContext: ../
      Dockerfile: lambdas/getACSUsers/Dockerfile

      

Outputs:

  updateACSdbApi:
    Description: "API Gateway endpoint URL for Prod stage for updateACSdb function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/updateACSdb/"

  getACSUsersApi:
    Description: "API Gateway endpoint URL for Prod stage for getACSUsersFunction function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getACSUsersFunction/"

